/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  BADSidebar: [{
    type: 'autogenerated', 
    dirName: '.'
  }],

  // But you can create a sidebar manually
  
  /*
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Frameworks',
      items: ['Frameworks/intro'],
    },    
    {
      type: 'category',
      label: 'Areas of Focus',
      items: ['Areas of Focus/intro'],
    },
    {
      type: 'category',
      label: 'Solutions',
      items: ['Solutions/intro'],
    },
    {
      type: 'category',
      label: 'Tools',
      items: ['Tools/intro'],
    },
  ],

*/
}; 

module.exports = sidebars;
